import { describe, it, expect } from "vitest";
import { parseMarkdownFrontmatterContent } from "@sentry/dotagents-lib";
import {
  markManagedMarkdownSubagent,
  hasDotagentsMarkdownSubagentMarker,
  hasDotagentsTomlSubagentMarker,
  serializeMarkdownSubagent,
  DOTAGENTS_SUBAGENT_MARKER,
} from "./format.js";

describe("serializeMarkdownSubagent", () => {
  it("serializes simple frontmatter fields", () => {
    const content = serializeMarkdownSubagent(
      {
        description: "Review code.",
        mode: "subagent",
      },
      "Review the diff.",
    );

    expect(content).toContain('description: "Review code."');
    expect(content).toContain('mode: "subagent"');
    expect(content).toContain("Review the diff.");
  });

  it("serializes nested frontmatter objects using block YAML", () => {
    const content = serializeMarkdownSubagent(
      {
        name: "code-reviewer",
        description: "Review code.",
        dotagents_native: {
          codex: [
            'name = "code_reviewer"',
            'description = "Review code."',
            "",
          ].join("\n"),
        },
      },
      "Review the diff.",
    );

    expect(content).toContain("dotagents_native:\n  codex: |+");
    expect(content).not.toContain('dotagents_native: {"codex"');

    const parsed = parseMarkdownFrontmatterContent(content, "subagent.md");
    expect(parsed.meta["dotagents_native"]).toEqual({
      codex: 'name = "code_reviewer"\ndescription = "Review code."\n',
    });
  });

  it("preserves trailing blank lines in nested native content", () => {
    const nativeContent = [
      'name = "code_reviewer"',
      'description = "Review code."',
      "",
      "",
    ].join("\n");
    const content = serializeMarkdownSubagent(
      {
        name: "code-reviewer",
        description: "Review code.",
        dotagents_native: {
          codex: nativeContent,
        },
      },
      "Review the diff.",
    );

    expect(content).toContain("dotagents_native:\n  codex: |+");

    const parsed = parseMarkdownFrontmatterContent(content, "subagent.md");
    expect(parsed.meta["dotagents_native"]).toEqual({
      codex: nativeContent,
    });
  });
});

describe("markManagedMarkdownSubagent", () => {
  it("wraps markdown without frontmatter in a managed header", () => {
    const content = "Review the current diff.\n";

    const marked = markManagedMarkdownSubagent(content);

    expect(marked).toBe(`---
# ${DOTAGENTS_SUBAGENT_MARKER}
---

Review the current diff.
`);
    expect(hasDotagentsMarkdownSubagentMarker(marked)).toBe(true);
  });

  it("preserves a BOM when wrapping markdown without frontmatter", () => {
    const content = "\uFEFFReview the current diff.\n";

    const marked = markManagedMarkdownSubagent(content);

    expect(marked).toBe(`\uFEFF---
# ${DOTAGENTS_SUBAGENT_MARKER}
---

Review the current diff.
`);
    expect(hasDotagentsMarkdownSubagentMarker(marked)).toBe(true);
  });

  it("marks markdown with a BOM and spaced frontmatter opener", () => {
    const content = "\uFEFF---   \nname: code-reviewer\n---\n\nReview code.\n";

    const marked = markManagedMarkdownSubagent(content);

    expect(marked).toContain(`# ${DOTAGENTS_SUBAGENT_MARKER}`);
    const parsed = parseMarkdownFrontmatterContent(marked, "subagent.md");
    expect(parsed.meta["name"]).toBe("code-reviewer");
  });

  it("does not treat marker text in the body as a managed header", () => {
    const content = `---
name: code-reviewer
---

The phrase ${DOTAGENTS_SUBAGENT_MARKER} appears in instructions.
`;

    const marked = markManagedMarkdownSubagent(content);

    expect(marked).toMatch(/^---\n# Generated by dotagents/);
    expect(hasDotagentsMarkdownSubagentMarker(content)).toBe(false);
    expect(hasDotagentsMarkdownSubagentMarker(marked)).toBe(true);
  });

  it("does not treat a TOML-style marker as a managed markdown header", () => {
    const content = `# ${DOTAGENTS_SUBAGENT_MARKER}
---
name: code-reviewer
---

Review the current diff.
`;

    expect(hasDotagentsMarkdownSubagentMarker(content)).toBe(false);
    expect(hasDotagentsTomlSubagentMarker(content)).toBe(true);
  });
});
