import { stringify as tomlStringify } from "smol-toml";
import { isSerializedObject, type SerializedObject } from "@sentry/dotagents-lib";
import { isString } from "../utils/type-guards.js";

export const DOTAGENTS_SUBAGENT_MARKER = "Generated by dotagents. Edit agents.toml instead.";
const DOTAGENTS_SUBAGENT_MARKER_RE = escapeRegExp(DOTAGENTS_SUBAGENT_MARKER);
const MANAGED_MARKDOWN_SUBAGENT_RE = new RegExp(
  `^\\uFEFF?---[ \\t]*\\r?\\n# ${DOTAGENTS_SUBAGENT_MARKER_RE}\\r?\\n`,
);
const MANAGED_TOML_SUBAGENT_RE = new RegExp(
  `^\\uFEFF?# ${DOTAGENTS_SUBAGENT_MARKER_RE}\\r?\\n`,
);

export function serializeMarkdownSubagent(
  fields: SerializedObject,
  instructions: string,
): string {
  const lines = ["---", `# ${DOTAGENTS_SUBAGENT_MARKER}`];

  for (const [key, value] of Object.entries(fields)) {
    appendYamlField(lines, key, value);
  }

  lines.push("---", "", instructions.trim(), "");
  return lines.join("\n");
}

/** Insert the dotagents marker into markdown subagent frontmatter. */
export function markManagedMarkdownSubagent(content: string): string {
  if (hasDotagentsMarkdownSubagentMarker(content)) {return content;}
  const marked = content.replace(
    /^(\uFEFF?---[ \t]*\r?\n)/,
    (opening) => `${opening}# ${DOTAGENTS_SUBAGENT_MARKER}\n`,
  );
  if (marked !== content) {return marked;}

  const hasBom = content.startsWith("\uFEFF");
  const body = hasBom ? content.slice(1) : content;
  return `${hasBom ? "\uFEFF" : ""}---\n# ${DOTAGENTS_SUBAGENT_MARKER}\n---\n\n${body}`;
}

/** Whether Markdown content has the dotagents marker in its generated frontmatter header. */
export function hasDotagentsMarkdownSubagentMarker(content: string): boolean {
  return MANAGED_MARKDOWN_SUBAGENT_RE.test(content);
}

/** Whether TOML content has the dotagents marker in its generated header. */
export function hasDotagentsTomlSubagentMarker(content: string): boolean {
  return MANAGED_TOML_SUBAGENT_RE.test(content);
}

export function serializeCodexSubagent(
  fields: SerializedObject,
): string {
  const doc: SerializedObject = {};
  for (const [key, value] of Object.entries(fields)) {
    if (value !== undefined) {
      doc[key] = value;
    }
  }

  return `# ${DOTAGENTS_SUBAGENT_MARKER}\n${tomlStringify(doc)}`;
}

export function markManagedTomlSubagent(content: string): string {
  if (hasDotagentsTomlSubagentMarker(content)) {return content;}
  return `# ${DOTAGENTS_SUBAGENT_MARKER}\n${content}`;
}

function escapeRegExp(value: string): string {
  return value.replaceAll(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function appendYamlField<Value>(
  lines: string[],
  key: string,
  value: Value,
  indent = 0,
): void {
  if (value === undefined) {return;}

  const prefix = " ".repeat(indent);
  if (isSerializedObject(value)) {
    const entries = Object.entries(value);
    if (entries.length === 0) {
      lines.push(`${prefix}${toYamlKey(key)}: {}`);
      return;
    }
    lines.push(`${prefix}${toYamlKey(key)}:`);
    for (const [childKey, childValue] of entries) {
      appendYamlField(lines, childKey, childValue, indent + 2);
    }
    return;
  }

  if (isString(value) && value.includes("\n")) {
    const chomp = value.endsWith("\n") ? "|+" : "|-";
    const body = value;
    lines.push(`${prefix}${toYamlKey(key)}: ${chomp}`);
    for (const line of body.split(/\r?\n/)) {
      lines.push(`${prefix}  ${line}`);
    }
    return;
  }

  const serialized = JSON.stringify(value);
  if (serialized !== undefined) {
    lines.push(`${prefix}${toYamlKey(key)}: ${serialized}`);
  }
}

function toYamlKey(key: string): string {
  if (/^[A-Za-z_][A-Za-z0-9_-]*$/.test(key)) {
    return key;
  }
  return JSON.stringify(key);
}
