import { existsSync, realpathSync } from "node:fs";
import { join, relative } from "node:path";
import type { PluginDeclaration } from "../types.js";
import { selectedAgentIds } from "../targets.js";
import { stableJson } from "../managed-files.js";
import { legacyManifestString, manifestString } from "./manifest-values.js";
import type { RuntimeOutput } from "./types.js";
import { normalizePluginRuntimeLayout, type PluginRuntimeRoot } from "./layout.js";
import type { SerializedObject } from "@sentry/dotagents-lib";

/** Lists managed plugin marketplace files that may be generated or pruned. */
export function marketplaceOutputPaths(root: PluginRuntimeRoot): string[] {
  const layout = normalizePluginRuntimeLayout(root);
  return [
    layout.codexMarketplacePath,
    layout.claudeMarketplacePath,
    layout.copilotMarketplacePath,
    layout.cursorMarketplacePath,
  ];
}

/** Returns the first Copilot catalog that takes precedence over dotagents output. */
export function copilotMarketplaceConflict(root: PluginRuntimeRoot): string | undefined {
  const layout = normalizePluginRuntimeLayout(root);
  const managedRealPath = tryRealpath(layout.copilotMarketplacePath);
  return [
    join(layout.copilotMarketplaceRoot, "marketplace.json"),
    join(layout.copilotMarketplaceRoot, ".plugin", "marketplace.json"),
  ].find((filePath) => (
    existsSync(filePath) &&
    (managedRealPath === undefined || tryRealpath(filePath) !== managedRealPath)
  ));
}

function tryRealpath(filePath: string): string | undefined {
  try {
    return realpathSync(filePath);
  } catch {
    return undefined;
  }
}

export function copilotMarketplaceConflictMessage(
  root: PluginRuntimeRoot,
  conflictPath: string,
): string {
  const layout = normalizePluginRuntimeLayout(root);
  return `Copilot will ignore the dotagents marketplace at ${layout.copilotMarketplacePath} because a higher-priority marketplace exists: ${conflictPath}. Remove or rename the higher-priority file, or exclude "copilot" from the plugin targets.`;
}

/** Builds target-specific marketplace JSON outputs for selected plugins. */
export function marketplaceOutputs(
  agentIds: string[],
  root: PluginRuntimeRoot,
  plugins: PluginDeclaration[],
): RuntimeOutput[] {
  if (plugins.length === 0) {return [];}
  const layout = normalizePluginRuntimeLayout(root);

  const outputs: RuntimeOutput[] = [];
  const claudePlugins = plugins.filter((plugin) => selectedAgentIds(agentIds, plugin).includes("claude"));
  const copilotPlugins = plugins.filter((plugin) => selectedAgentIds(agentIds, plugin).includes("copilot"));
  const cursorPlugins = plugins.filter((plugin) => selectedAgentIds(agentIds, plugin).includes("cursor"));
  const codexPlugins = plugins.filter((plugin) => selectedAgentIds(agentIds, plugin).includes("codex"));

  if (claudePlugins.length > 0) {
    const filePath = layout.claudeMarketplacePath;
    outputs.push({
      agent: "claude",
      filePath,
      content: stableJson(pathMarketplace(layout.claudeMarketplaceRoot, "dotagents", claudePlugins)),
    });
  }
  if (copilotPlugins.length > 0) {
    const filePath = layout.copilotMarketplacePath;
    outputs.push({
      agent: "copilot",
      filePath,
      content: stableJson(pathMarketplace(layout.copilotMarketplaceRoot, "dotagents", copilotPlugins)),
    });
  }
  if (cursorPlugins.length > 0) {
    const filePath = layout.cursorMarketplacePath;
    outputs.push({
      agent: "cursor",
      filePath,
      content: stableJson(pathMarketplace(layout.cursorMarketplaceRoot, "dotagents", cursorPlugins)),
    });
  }
  if (codexPlugins.length > 0) {
    const filePath = layout.codexMarketplacePath;
    outputs.push({
      agent: "codex",
      filePath,
      content: stableJson(codexMarketplace(layout.codexMarketplaceRoot, "dotagents-local", codexPlugins)),
    });
  }

  return outputs;
}

function pathMarketplace(
  projectRoot: string,
  name: string,
  plugins: PluginDeclaration[],
): SerializedObject {
  return {
    description: "Generated by dotagents",
    name,
    owner: {
      name: "dotagents",
    },
    plugins: plugins
      .toSorted((a, b) => a.name.localeCompare(b.name))
      .map((plugin) => pathMarketplaceEntry(projectRoot, plugin)),
  };
}

/**
 * Claude, Copilot, and Cursor marketplace projections use path strings instead
 * of Codex's structured local source objects, so keep this format separate.
 */
function pathMarketplaceEntry(
  projectRoot: string,
  plugin: PluginDeclaration,
): SerializedObject {
  const entry: SerializedObject = {
    name: plugin.name,
    source: `./${relative(projectRoot, plugin.pluginDir).split("\\").join("/")}`,
  };
  const description = manifestString(plugin.manifest, "description");
  if (description) {entry["description"] = description;}
  const version = manifestString(plugin.manifest, "version");
  if (version) {entry["version"] = version;}
  return entry;
}

function codexMarketplace(
  projectRoot: string,
  name: string,
  plugins: PluginDeclaration[],
): SerializedObject {
  return {
    interface: {
      displayName: "Dotagents Plugins",
    },
    name,
    owner: {
      name: "dotagents",
    },
    plugins: plugins
      .toSorted((a, b) => a.name.localeCompare(b.name))
      .map((plugin) => codexMarketplaceEntry(projectRoot, plugin)),
  };
}

function codexMarketplaceEntry(
  projectRoot: string,
  plugin: PluginDeclaration,
): SerializedObject {
  const entry: SerializedObject = {
    category: legacyManifestString(plugin.manifest, "category") ?? "Productivity",
    name: plugin.name,
    policy: {
      authentication: "ON_INSTALL",
      installation: "AVAILABLE",
    },
    source: {
      path: `./${relative(projectRoot, plugin.pluginDir).split("\\").join("/")}`,
      source: "local",
    },
  };
  const description = manifestString(plugin.manifest, "description");
  if (description) {entry["description"] = description;}
  const version = manifestString(plugin.manifest, "version");
  if (version) {entry["version"] = version;}
  return entry;
}
