import { existsSync } from "node:fs";
import { lstat, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { reconcileManagedMcpConfig } from "../../targets/mcp-writer.js";
import type { McpDeclaration } from "../../targets/types.js";
import { isStandardPluginManifest, type PluginMcpConfig } from "../schema.js";
import { selectedAgentIds } from "../targets.js";
import type { PluginDeclaration } from "../types.js";
import type { LoadedStandardMcp } from "./manifests.js";
import type { PluginRuntimeLayout } from "./layout.js";
import type { PluginVerifyIssue, PluginWriteWarning } from "./types.js";

const DATA_MARKER = "Generated by dotagents. Plugin runtime data; removed when the plugin is uninstalled.\n";

export interface OpenCodePluginMcpResult {
  written: number;
  pruned: string[];
  issues: PluginVerifyIssue[];
}

export async function reconcileOpenCodePluginMcp(
  agentIds: string[],
  plugins: PluginDeclaration[],
  loadedMcp: ReadonlyMap<string, LoadedStandardMcp>,
  layout: PluginRuntimeLayout,
  reservedNames: Iterable<string>,
  mode: "inspect" | "apply",
  warnings: PluginWriteWarning[],
): Promise<OpenCodePluginMcpResult> {
  const issues: PluginVerifyIssue[] = [];
  const pruned = await reconcilePluginDataDirs(plugins, layout, mode, issues);
  const declarations: McpDeclaration[] = [];

  if (agentIds.includes("opencode")) {
    for (const plugin of plugins) {
      if (!selectedAgentIds(agentIds, plugin).includes("opencode")) {continue;}
      if (!isStandardPluginManifest(plugin.manifest)) {continue;}
      const mcp = loadedMcp.get(plugin.name)?.config;
      if (!mcp) {continue;}
      declarations.push(...await openCodeDeclarations(plugin, mcp, layout, mode, warnings, issues));
    }
  }

  const result = await reconcileManagedMcpConfig({
    agentId: "opencode",
    servers: declarations,
    target: { filePath: layout.opencodeMcpPath, shared: true },
    statePath: layout.opencodeMcpStatePath,
    protectedNames: reservedNames,
    mode,
  });

  const reported = mode === "inspect"
    ? result.issues
    : [...result.unresolved, ...result.skipped];
  for (const { issue } of reported) {
    const finding = { agent: "opencode", name: "mcp", issue };
    issues.push(finding);
    if (mode === "apply") {
      warnings.push({ agent: finding.agent, name: finding.name, message: finding.issue });
    }
  }

  return {
    written: result.written.length,
    pruned: [...pruned, ...result.removed],
    issues,
  };
}

async function openCodeDeclarations(
  plugin: PluginDeclaration,
  mcp: PluginMcpConfig,
  layout: PluginRuntimeLayout,
  mode: "inspect" | "apply",
  warnings: PluginWriteWarning[],
  issues: PluginVerifyIssue[],
): Promise<McpDeclaration[]> {
  const entries = Object.entries(mcp.mcpServers);
  const hasStdio = entries.some(([, server]) => server.type === "stdio");
  const dataDir = join(layout.pluginDataDir, plugin.name);
  if (hasStdio && !await ensurePluginDataDir(dataDir, mode)) {
    const message = `OpenCode plugin data directory is missing or not managed by dotagents: ${dataDir}`;
    if (mode === "apply") {warnings.push({ agent: "opencode", name: plugin.name, message });}
    issues.push({ agent: "opencode", name: plugin.name, issue: message });
  }

  const declarations: McpDeclaration[] = [];
  for (const [serverName, server] of entries) {
    const name = `plugin.${plugin.name}.${serverName}`;
    if (server.type !== "stdio") {
      declarations.push({
        name,
        url: server.url,
        ...(server.headers && { headers: server.headers }),
      });
      continue;
    }
    if (!await isManagedPluginDataDir(dataDir)) {continue;}

    const pluginRoot = resolve(plugin.pluginDir);
    const expand = (value: string): string => value
      .replaceAll("${PLUGIN_ROOT}", pluginRoot)
      .replaceAll("${PLUGIN_DATA}", dataDir);
    const command = server.command.startsWith("./")
      ? join(pluginRoot, server.command.slice(2))
      : server.command;
    const envValues: Record<string, string> = {
      PLUGIN_ROOT: pluginRoot,
      PLUGIN_DATA: dataDir,
    };
    for (const [key, value] of Object.entries(server.env ?? {})) {
      envValues[key] = expand(value);
    }
    declarations.push({
      name,
      command,
      ...(server.args && { args: server.args.map(expand) }),
      envValues,
      ...(server.cwd && { cwd: expand(server.cwd) }),
    });
  }
  return declarations;
}

async function ensurePluginDataDir(dataDir: string, mode: "inspect" | "apply"): Promise<boolean> {
  if (existsSync(dataDir)) {return isManagedPluginDataDir(dataDir);}
  if (mode === "inspect") {return false;}
  await mkdir(dataDir, { recursive: true });
  await writeFile(join(dataDir, ".dotagents-managed"), DATA_MARKER, "utf-8");
  return true;
}

async function isManagedPluginDataDir(dataDir: string): Promise<boolean> {
  try {
    if (!(await lstat(dataDir)).isDirectory()) {return false;}
    return await readFile(join(dataDir, ".dotagents-managed"), "utf-8") === DATA_MARKER;
  } catch {
    return false;
  }
}

async function reconcilePluginDataDirs(
  plugins: PluginDeclaration[],
  layout: PluginRuntimeLayout,
  mode: "inspect" | "apply",
  issues: PluginVerifyIssue[],
): Promise<string[]> {
  if (!existsSync(layout.pluginDataDir)) {return [];}
  const installed = new Set(plugins.map((plugin) => plugin.name));
  const pruned: string[] = [];
  for (const entry of await readdir(layout.pluginDataDir, { withFileTypes: true })) {
    if (!entry.isDirectory() || installed.has(entry.name)) {continue;}
    const dataDir = join(layout.pluginDataDir, entry.name);
    if (!await isManagedPluginDataDir(dataDir)) {continue;}
    if (mode === "inspect") {
      issues.push({
        agent: "opencode",
        name: entry.name,
        issue: `OpenCode plugin data directory is stale: ${dataDir}`,
      });
      continue;
    }
    await rm(dataDir, { recursive: true });
    pruned.push(dataDir);
  }
  return pruned;
}
