import { existsSync } from "node:fs";
import { lstat, mkdtemp, mkdir, readFile, readlink, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { parse as parseJSONC } from "jsonc-parser";
import type { PluginDeclaration } from "../types.js";
import { AGENT_PLUGIN_SCHEMA, isStandardPluginManifest } from "../schema.js";
import {
  prunePluginOutputs,
  projectedPiSkillNames,
  verifyPluginOutputs,
  writePluginOutputs,
} from "./writer.js";
import type { SerializedObject } from "@sentry/dotagents-lib";

describe("plugin writer", () => {
  let root: string;

  beforeEach(async () => {
    root = await mkdtemp(join(tmpdir(), "dotagents-plugin-writer-"));
  });

  afterEach(async () => {
    await rm(root, { recursive: true });
  });

  async function plugin(
    name: string,
    overrides: Partial<PluginDeclaration> = {},
  ): Promise<PluginDeclaration> {
    const pluginDir = join(root, ".agents", "plugins", name);
    await mkdir(join(pluginDir, "skills"), { recursive: true });
    await mkdir(join(pluginDir, "commands"), { recursive: true });
    await mkdir(join(pluginDir, "agents"), { recursive: true });
    const manifest = (overrides.manifest && isStandardPluginManifest(overrides.manifest)
      ? overrides.manifest
      : {
          name,
          version: "1.0.0",
          description: `Tools for ${name}`,
          category: "Coding",
          author: { name: "Sentry" },
          ...overrides.manifest,
        }) as PluginDeclaration["manifest"];
    return {
      name,
      source: `path:.agents/plugins/${name}`,
      pluginDir,
      manifest,
      nativeSource: overrides.nativeSource,
      targets: overrides.targets,
    };
  }

  async function expectSymlinkTarget(linkPath: string, expectedTarget: string): Promise<void> {
    expect((await lstat(linkPath)).isSymbolicLink()).toBe(true);
    expect(resolve(dirname(linkPath), await readlink(linkPath))).toBe(resolve(expectedTarget));
  }

  function componentMarkerContent(linkPath: string, targetPath: string): string {
    return `managedBy=dotagents\ntarget=${JSON.stringify(relative(dirname(linkPath), targetPath))}\n`;
  }

  async function writePluginSkill(pluginDir: string, name: string): Promise<void> {
    await mkdir(join(pluginDir, "skills", name), { recursive: true });
    await writeFile(
      join(pluginDir, "skills", name, "SKILL.md"),
      `---\nname: ${name}\ndescription: Plugin QA\n---\n`,
      "utf-8",
    );
  }

  it("writes deterministic marketplace outputs for runtimes that need projections", async () => {
    const alpha = await plugin("alpha-tools");
    const beta = await plugin("beta-tools");

    const result = await writePluginOutputs(
      ["cursor", "codex", "claude"],
      [beta, alpha],
      root,
    );

    expect(result.warnings).toEqual([]);
    expect(result.written).toBe(9);
    const codexMarketplace = JSON.parse(await readFile(join(root, ".agents", "plugins", "marketplace.json"), "utf-8")) as SerializedObject;
    expect(codexMarketplace).toEqual({
      interface: {
        displayName: "Dotagents Plugins",
      },
      name: "dotagents-local",
      owner: {
        name: "dotagents",
      },
      plugins: [
        {
          category: "Coding",
          description: "Tools for alpha-tools",
          name: "alpha-tools",
          policy: {
            authentication: "ON_INSTALL",
            installation: "AVAILABLE",
          },
          source: {
            path: "./.agents/plugins/alpha-tools",
            source: "local",
          },
          version: "1.0.0",
        },
        {
          category: "Coding",
          description: "Tools for beta-tools",
          name: "beta-tools",
          policy: {
            authentication: "ON_INSTALL",
            installation: "AVAILABLE",
          },
          source: {
            path: "./.agents/plugins/beta-tools",
            source: "local",
          },
          version: "1.0.0",
        },
      ],
    });
    const codexPlugin = (codexMarketplace["plugins"] as Array<{ source: { path: string } }>)[0]!;
    expect(resolve(root, codexPlugin["source"].path)).toBe(alpha.pluginDir);

    const claudeMarketplaceJson = await readFile(join(root, ".claude-plugin", "marketplace.json"), "utf-8");
    expect(claudeMarketplaceJson).toBe(`{
  "description": "Generated by dotagents",
  "name": "dotagents",
  "owner": {
    "name": "dotagents"
  },
  "plugins": [
    {
      "description": "Tools for alpha-tools",
      "name": "alpha-tools",
      "source": "./.agents/plugins/alpha-tools",
      "version": "1.0.0"
    },
    {
      "description": "Tools for beta-tools",
      "name": "beta-tools",
      "source": "./.agents/plugins/beta-tools",
      "version": "1.0.0"
    }
  ]
}
`);
    const claudeMarketplace = JSON.parse(claudeMarketplaceJson) as { plugins: Array<{ source: string }> };
    expect(resolve(root, claudeMarketplace["plugins"][0]!["source"])).toBe(alpha.pluginDir);
    expect(await readFile(join(root, ".cursor-plugin", "marketplace.json"), "utf-8")).toBe(claudeMarketplaceJson);

    const claudeManifest = JSON.parse(await readFile(join(root, ".agents", "plugins", "alpha-tools", ".claude-plugin", "plugin.json"), "utf-8")) as SerializedObject;
    expect(claudeManifest["skills"]).toBe("./skills");
    expect(claudeManifest["commands"]).toBe("./commands");
    expect(claudeManifest["agents"]).toBeUndefined();
    expect(claudeManifest["category"]).toBeUndefined();
    expect(claudeManifest["metadata"]).toBeUndefined();

    const cursorManifest = JSON.parse(await readFile(join(root, ".agents", "plugins", "alpha-tools", ".cursor-plugin", "plugin.json"), "utf-8")) as SerializedObject;
    expect(cursorManifest["skills"]).toBe("./skills");
    expect(cursorManifest["commands"]).toBe("./commands");
    expect(cursorManifest["agents"]).toBe("./agents");
    expect(cursorManifest["metadata"]).toBeUndefined();

    const codexManifest = JSON.parse(await readFile(join(root, ".agents", "plugins", "alpha-tools", ".codex-plugin", "plugin.json"), "utf-8")) as SerializedObject;
    expect(codexManifest["skills"]).toBe("./skills");
    expect(codexManifest["commands"]).toBe("./commands");
    expect(codexManifest["agents"]).toBe("./agents");
    expect(codexManifest["interface"]).toEqual({
      capabilities: ["Interactive", "Write"],
      category: "Coding",
      developerName: "Sentry",
      displayName: "Alpha Tools",
      shortDescription: "Tools for alpha-tools",
    });

    expect(await verifyPluginOutputs(["cursor", "codex", "claude"], [beta, alpha], root)).toEqual([]);
  });

  it("uses default Codex categories for empty legacy category values", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: {
        name: "alpha-tools",
        category: "",
      },
    });

    await writePluginOutputs(["codex"], [alpha], root);

    const marketplace = JSON.parse(
      await readFile(join(root, ".agents", "plugins", "marketplace.json"), "utf-8"),
    ) as { plugins: Array<{ category: string }> };
    expect(marketplace.plugins[0]!.category).toBe("Productivity");

    const manifest = JSON.parse(
      await readFile(join(alpha.pluginDir, ".codex-plugin", "plugin.json"), "utf-8"),
    ) as { interface: { category: string } };
    expect(manifest.interface.category).toBe("Coding");
  });

  it("preserves explicit skills paths when repairing native manifests", async () => {
    for (const nativeSource of ["claude", "cursor"] as const) {
      const nativePlugin = await plugin(`${nativeSource}-tools`, {
        nativeSource,
        manifest: {
          name: `${nativeSource}-tools`,
          skills: "custom-skills",
        },
      });
      await mkdir(join(nativePlugin.pluginDir, "custom-skills"), { recursive: true });

      await writePluginOutputs([nativeSource], [nativePlugin], root);

      const manifest = JSON.parse(
        await readFile(join(nativePlugin.pluginDir, `.${nativeSource}-plugin`, "plugin.json"), "utf-8"),
      ) as { skills: string };
      expect(manifest.skills).toBe("./custom-skills");
    }
  });

  it("isolates invalid Agent Plugins MCP config from other components", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: {
        $schema: AGENT_PLUGIN_SCHEMA,
        name: "alpha-tools",
        description: "Portable tools",
      },
    });
    await writePluginSkill(alpha.pluginDir, "plugin-qa");
    await writeFile(join(alpha.pluginDir, "mcp.json"), JSON.stringify({
      $schema: "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json",
      mcpServers: {
        good: { type: "stdio", command: "node", args: ["server.js"] },
        bad: { type: "stdio", command: "node server.js" },
      },
    }));
    await writeFile(join(alpha.pluginDir, ".mcp.json"), JSON.stringify({ mcpServers: { legacy: {} } }));

    const result = await writePluginOutputs(["claude", "cursor", "codex"], [alpha], root);
    for (const dir of [".claude-plugin", ".cursor-plugin", ".codex-plugin"]) {
      const manifest = JSON.parse(await readFile(join(alpha.pluginDir, dir, "plugin.json"), "utf-8"));
      expect(manifest.skills).toBe("./skills");
      expect(manifest.mcpServers).toBe(`./${dir}/mcp.json`);
      expect(JSON.parse(await readFile(join(alpha.pluginDir, dir, "mcp.json"), "utf-8"))).toEqual({
        $schema: "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json",
        mcpServers: {
          good: { type: "stdio", command: "node", args: ["server.js"] },
        },
      });
      expect(existsSync(join(alpha.pluginDir, dir, "mcp.json.dotagents-managed"))).toBe(true);
    }
    expect(result.warnings.some((warning) => warning.message.includes('Invalid plugin MCP server "bad"'))).toBe(true);

    await writeFile(join(alpha.pluginDir, "mcp.json"), JSON.stringify({
      $schema: "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json",
      mcpServers: { bad: { type: "stdio", command: "node server.js" } },
    }));
    await writePluginOutputs(["claude", "cursor", "codex"], [alpha], root);
    for (const dir of [".claude-plugin", ".cursor-plugin", ".codex-plugin"]) {
      expect(existsSync(join(alpha.pluginDir, dir, "mcp.json"))).toBe(false);
      expect(existsSync(join(alpha.pluginDir, dir, "mcp.json.dotagents-managed"))).toBe(false);
      const manifest = JSON.parse(await readFile(join(alpha.pluginDir, dir, "plugin.json"), "utf-8"));
      expect(manifest.mcpServers).toBeUndefined();
    }
  });

  it("preserves unmanaged native MCP adapter files", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: {
        $schema: AGENT_PLUGIN_SCHEMA,
        name: "alpha-tools",
      },
    });
    await writeFile(join(alpha.pluginDir, "mcp.json"), JSON.stringify({
      $schema: "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json",
      mcpServers: {
        good: { type: "stdio", command: "node" },
        bad: { type: "stdio", command: "node server.js" },
      },
    }));
    const adapterMcpPath = join(alpha.pluginDir, ".claude-plugin", "mcp.json");
    await mkdir(join(alpha.pluginDir, ".claude-plugin"), { recursive: true });
    await writeFile(adapterMcpPath, '{"user":"owned"}\n');

    const result = await writePluginOutputs(["claude"], [alpha], root);

    expect(await readFile(adapterMcpPath, "utf-8")).toBe('{"user":"owned"}\n');
    expect(existsSync(`${adapterMcpPath}.dotagents-managed`)).toBe(false);
    const manifest = JSON.parse(
      await readFile(join(alpha.pluginDir, ".claude-plugin", "plugin.json"), "utf-8"),
    ) as SerializedObject;
    expect(manifest["mcpServers"]).toBeUndefined();
    expect(result.warnings.some((warning) => warning.message.includes("MCP adapter exists and is not managed"))).toBe(true);
  });

  it("skips component symlinks that escape the plugin bundle", async () => {
    const alpha = await plugin("alpha-tools");
    const outsideFile = join(root, "outside.md");
    await writeFile(outsideFile, "secret");
    await symlink(outsideFile, join(alpha.pluginDir, "agents", "evil.md"));

    const result = await writePluginOutputs(["opencode"], [alpha], root);

    expect(existsSync(join(root, ".opencode", "agents", "evil.md"))).toBe(false);
    expect(result.warnings).toContainEqual({
      agent: "opencode",
      name: "alpha-tools",
      message: `Plugin agent resolves outside the plugin bundle and was skipped: ${join(alpha.pluginDir, "agents", "evil.md")}`,
    });
  });

  it("warns when a Grok projection collides with a file", async () => {
    const alpha = await plugin("alpha-tools");
    const dest = join(root, ".grok", "plugins", "alpha-tools");
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, "owned by user\n");

    const result = await writePluginOutputs(["grok"], [alpha], root);

    expect(result.warnings).toEqual([{
      agent: "grok",
      name: "alpha-tools",
      message: `Grok plugin projection exists and is not managed by dotagents: ${dest}`,
    }]);
    expect(await readFile(dest, "utf-8")).toBe("owned by user\n");
  });

  it("accepts contained plugin component directories whose names start with two dots", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: { name: "alpha-tools", skills: "..skills" },
    });
    const skillDir = join(alpha.pluginDir, "..skills", "plugin-qa");
    await mkdir(skillDir, { recursive: true });
    await writeFile(join(skillDir, "SKILL.md"), `---\nname: plugin-qa\ndescription: Plugin QA\n---\n`);

    const result = await writePluginOutputs(["opencode"], [alpha], root);

    expect(result.warnings).toEqual([]);
    await expectSymlinkTarget(join(root, ".opencode", "skills", "plugin-qa"), skillDir);
  });

  it("projects explicit runtime component paths before conventional discovery", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: {
        agents: "custom-agents",
        commands: ["cmds/review.md"],
        hooks: "config/hooks.json",
        mcpServers: "config/mcp.json",
        rules: "cursor-rules",
        skills: "plugin-skills",
      },
    });

    const result = await writePluginOutputs(["claude", "cursor"], [alpha], root);

    expect(result.warnings).toEqual([]);
    expect(result.written).toBe(4);
    const claudeManifest = JSON.parse(await readFile(join(alpha.pluginDir, ".claude-plugin", "plugin.json"), "utf-8")) as SerializedObject;
    expect(claudeManifest["agents"]).toBeUndefined();
    expect(claudeManifest["commands"]).toEqual(["./cmds/review.md"]);
    expect(claudeManifest["hooks"]).toBe("./config/hooks.json");
    expect(claudeManifest["mcpServers"]).toBe("./config/mcp.json");
    expect(claudeManifest["skills"]).toBe("./plugin-skills");

    const cursorManifest = JSON.parse(await readFile(join(alpha.pluginDir, ".cursor-plugin", "plugin.json"), "utf-8")) as SerializedObject;
    expect(cursorManifest["agents"]).toBe("./custom-agents");
    expect(cursorManifest["commands"]).toEqual(["./cmds/review.md"]);
    expect(cursorManifest["hooks"]).toBe("./config/hooks.json");
    expect(cursorManifest["mcpServers"]).toBe("./config/mcp.json");
    expect(cursorManifest["rules"]).toBe("./cursor-rules");
    expect(cursorManifest["skills"]).toBe("./plugin-skills");
  });

  it("skips unsafe runtime component paths in generated manifests", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: {
        skills: "../outside",
      },
    });

    const result = await writePluginOutputs(["claude", "cursor", "codex"], [alpha], root);

    expect(result.written).toBe(6);
    expect(result.warnings).toEqual([
      {
        agent: "plugin",
        name: "alpha-tools",
        message: 'Plugin component path "../outside" for "skills" is not a safe relative path and was skipped.',
      },
      {
        agent: "plugin",
        name: "alpha-tools",
        message: 'Plugin component path "../outside" for "skills" is not a safe relative path and was skipped.',
      },
      {
        agent: "plugin",
        name: "alpha-tools",
        message: 'Plugin component path "../outside" for "skills" is not a safe relative path and was skipped.',
      },
    ]);
    const claudeManifest = JSON.parse(await readFile(join(alpha.pluginDir, ".claude-plugin", "plugin.json"), "utf-8")) as SerializedObject;
    const cursorManifest = JSON.parse(await readFile(join(alpha.pluginDir, ".cursor-plugin", "plugin.json"), "utf-8")) as SerializedObject;
    const codexManifest = JSON.parse(await readFile(join(alpha.pluginDir, ".codex-plugin", "plugin.json"), "utf-8")) as SerializedObject;
    expect(claudeManifest["skills"]).toBeUndefined();
    expect(cursorManifest["skills"]).toBeUndefined();
    expect(codexManifest["skills"]).toBeUndefined();
  });

  it("skips backslash-rooted runtime component paths in generated manifests", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: {
        skills: "\\outside",
      },
    });

    const result = await writePluginOutputs(["codex"], [alpha], root);

    expect(result.warnings).toEqual([
      {
        agent: "plugin",
        name: "alpha-tools",
        message: 'Plugin component path "\\outside" for "skills" is not a safe relative path and was skipped.',
      },
    ]);
    const codexManifest = JSON.parse(await readFile(join(alpha.pluginDir, ".codex-plugin", "plugin.json"), "utf-8")) as SerializedObject;
    expect(codexManifest["skills"]).toBeUndefined();
  });

  it("does not overwrite unmanaged marketplace files", async () => {
    const alpha = await plugin("alpha-tools");
    await mkdir(join(root, ".claude-plugin"), { recursive: true });
    await writeFile(join(root, ".claude-plugin", "marketplace.json"), "{ \"name\": \"mine\" }\n", "utf-8");

    const result = await writePluginOutputs(["claude"], [alpha], root);

    expect(result.written).toBe(1);
    expect(result.warnings).toEqual([
      {
        agent: "claude",
        name: "marketplace",
        message: `Plugin marketplace exists and is not managed by dotagents: ${join(root, ".claude-plugin", "marketplace.json")}`,
      },
    ]);
    expect(await readFile(join(root, ".claude-plugin", "marketplace.json"), "utf-8")).toBe("{ \"name\": \"mine\" }\n");
    expect(existsSync(join(root, ".agents", "plugins", "alpha-tools", ".claude-plugin", "plugin.json"))).toBe(true);
  });

  it("does not overwrite unmanaged Codex marketplace files", async () => {
    const alpha = await plugin("alpha-tools");
    await writeFile(join(root, ".agents", "plugins", "marketplace.json"), "{ \"name\": \"mine\" }\n", "utf-8");

    const result = await writePluginOutputs(["codex"], [alpha], root);

    expect(result.warnings).toEqual([
      {
        agent: "codex",
        name: "marketplace",
        message: `Plugin marketplace exists and is not managed by dotagents: ${join(root, ".agents", "plugins", "marketplace.json")}`,
      },
    ]);
    expect(await readFile(join(root, ".agents", "plugins", "marketplace.json"), "utf-8")).toBe("{ \"name\": \"mine\" }\n");
    expect(existsSync(join(root, ".agents", "plugins", "alpha-tools", ".codex-plugin", "plugin.json"))).toBe(true);
  });

  it.each([
    ["codex", "Codex", ".codex-plugin"],
    ["claude", "Claude", ".claude-plugin"],
    ["cursor", "Cursor", ".cursor-plugin"],
  ] as const)("does not overwrite unmanaged %s plugin manifests", async (agent, label, manifestDir) => {
    const alpha = await plugin("alpha-tools");
    const manifestPath = join(alpha.pluginDir, manifestDir, "plugin.json");
    await mkdir(join(alpha.pluginDir, manifestDir), { recursive: true });
    await writeFile(manifestPath, "{ \"name\": \"mine\" }\n", "utf-8");

    const result = await writePluginOutputs([agent], [alpha], root);

    expect(result.warnings).toEqual([
      {
        agent,
        name: "alpha-tools",
        message: `${label} plugin manifest exists and is not managed by dotagents: ${join(root, ".agents", "plugins", "alpha-tools", manifestDir, "plugin.json")}`,
      },
    ]);
    expect(await readFile(manifestPath, "utf-8")).toBe("{ \"name\": \"mine\" }\n");
  });

  it("does not generate runtime outputs when no agent targets are selected", async () => {
    const alpha = await plugin("alpha-tools");

    const result = await writePluginOutputs([], [alpha], root);

    expect(result).toEqual({ warnings: [], written: 0 });
    expect(existsSync(join(root, ".agents", "plugins", "marketplace.json"))).toBe(false);
    expect(existsSync(join(root, ".claude-plugin", "marketplace.json"))).toBe(false);
    expect(existsSync(join(root, ".cursor-plugin", "marketplace.json"))).toBe(false);
  });

  it("warns and skips plugin targets that are not configured agents", async () => {
    const alpha = await plugin("alpha-tools", { targets: ["codex"] });

    const result = await writePluginOutputs(["claude"], [alpha], root);

    expect(result.written).toBe(0);
    expect(result.warnings).toEqual([
      {
        agent: "codex",
        name: "alpha-tools",
        message: 'Plugin "alpha-tools" targets "codex", but "codex" is not listed in agents.',
      },
    ]);
    expect(existsSync(join(root, ".agents", "plugins", "marketplace.json"))).toBe(false);
    expect(existsSync(join(root, ".agents", "plugins", "alpha-tools", ".codex-plugin", "plugin.json"))).toBe(false);
  });

  it.each(["directory", "wrong-content file"] as const)(
    "does not treat a Grok marker %s as projection ownership",
    async (markerShape) => {
    const alpha = await plugin("alpha-tools");
    const dest = join(root, ".grok", "plugins", "alpha-tools");
    await mkdir(dest, { recursive: true });
    if (markerShape === "directory") {
      await mkdir(join(dest, ".dotagents-managed"));
    } else {
      await writeFile(join(dest, ".dotagents-managed"), "owned-by=user\n");
    }
    await writeFile(join(dest, "user.txt"), "keep\n");

    const result = await writePluginOutputs(["grok"], [alpha], root);

    expect(result).toEqual({
      written: 0,
      warnings: [{
        agent: "grok",
        name: "alpha-tools",
        message: `Grok plugin projection exists and is not managed by dotagents: ${dest}`,
      }],
    });
    expect(await readFile(join(dest, "user.txt"), "utf-8")).toBe("keep\n");
    },
  );

  it("projects plugin skills and agents into OpenCode native locations", async () => {
    const alpha = await plugin("alpha-tools");
    await writePluginSkill(alpha.pluginDir, "plugin-qa");
    await writeFile(
      join(alpha.pluginDir, "agents", "plugin-reviewer.md"),
      "---\ndescription: Plugin reviewer\n---\nReview plugin output.\n",
      "utf-8",
    );

    const result = await writePluginOutputs(["opencode"], [alpha], root);

    expect(result.warnings).toEqual([]);
    expect(result.written).toBe(2);
    await expectSymlinkTarget(
      join(root, ".opencode", "skills", "plugin-qa"),
      join(alpha.pluginDir, "skills", "plugin-qa"),
    );
    await expectSymlinkTarget(
      join(root, ".opencode", "agents", "plugin-reviewer.md"),
      join(alpha.pluginDir, "agents", "plugin-reviewer.md"),
    );
    expect(await verifyPluginOutputs(["opencode"], [alpha], root)).toEqual([]);
  });

  it("flattens portable plugin MCP into OpenCode and prunes only managed state", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: {
        $schema: AGENT_PLUGIN_SCHEMA,
        name: "alpha-tools",
        version: "1.0.0",
      },
    });
    await writeFile(join(alpha.pluginDir, "mcp.json"), JSON.stringify({
      $schema: "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json",
      mcpServers: {
        local: {
          type: "stdio",
          command: "node",
          args: ["${PLUGIN_ROOT}/server.mjs", "${OTHER}"],
          env: { CACHE_DIR: "${PLUGIN_DATA}/cache" },
          cwd: "./runtime",
        },
        "default-cwd": {
          type: "stdio",
          command: "node",
        },
        remote: {
          type: "streamable-http",
          url: "https://example.com/${DEPLOYMENT}/mcp",
          headers: { "X-Fixture": "Bearer ${TOKEN}" },
        },
      },
    }));
    const opencodePath = join(root, ".opencode", "opencode.jsonc");
    await mkdir(dirname(opencodePath), { recursive: true });
    await writeFile(opencodePath, [
      "{",
      "  // Preserve user config",
      '  "theme": "dark",',
      '  "mcp": { "manual": { "type": "local", "command": ["manual"] } },',
      "}",
      "",
    ].join("\n"));

    const result = await writePluginOutputs(["opencode"], [alpha], root);

    expect(result.warnings).toEqual([]);
    const raw = await readFile(opencodePath, "utf-8");
    expect(raw).toContain("// Preserve user config");
    const config = parseJSONC(raw) as { mcp: SerializedObject };
    expect(config.mcp["manual"]).toEqual({ type: "local", command: ["manual"] });
    expect(config.mcp["plugin.alpha-tools.remote"]).toEqual({
      type: "remote",
      url: "https://example.com/${DEPLOYMENT}/mcp",
      headers: { "X-Fixture": "Bearer ${TOKEN}" },
    });
    const dataDir = join(root, ".agents", "plugin-data", "alpha-tools");
    expect(config.mcp["plugin.alpha-tools.local"]).toEqual({
      type: "local",
      command: ["node", join(alpha.pluginDir, "server.mjs"), "${OTHER}"],
      cwd: join(alpha.pluginDir, "runtime"),
      environment: {
        CACHE_DIR: `${dataDir}/cache`,
        PLUGIN_DATA: dataDir,
        PLUGIN_ROOT: alpha.pluginDir,
      },
    });
    expect(config.mcp["plugin.alpha-tools.default-cwd"]).toEqual({
      type: "local",
      command: ["node"],
      cwd: alpha.pluginDir,
      environment: {
        PLUGIN_DATA: dataDir,
        PLUGIN_ROOT: alpha.pluginDir,
      },
    });
    expect(existsSync(join(dataDir, ".dotagents-managed"))).toBe(true);
    expect(JSON.parse(await readFile(
      join(root, ".agents", "plugin-mcp", "opencode.json"),
      "utf-8",
    ))).toEqual({
      version: 1,
      servers: [
        "plugin.alpha-tools.default-cwd",
        "plugin.alpha-tools.local",
        "plugin.alpha-tools.remote",
      ],
    });
    expect(await verifyPluginOutputs(["opencode"], [alpha], root)).toEqual([]);

    await writePluginOutputs([], [], root);

    const prunedRaw = await readFile(opencodePath, "utf-8");
    expect(prunedRaw).toContain("// Preserve user config");
    const prunedConfig = parseJSONC(prunedRaw) as {
      mcp: SerializedObject;
    };
    expect(prunedConfig.mcp).toEqual({ manual: { type: "local", command: ["manual"] } });
    expect(existsSync(dataDir)).toBe(false);
    expect(existsSync(join(root, ".agents", "plugin-mcp", "opencode.json"))).toBe(false);
  });

  it("keeps component ownership markers outside the valid skill-name namespace", async () => {
    const alpha = await plugin("alpha-tools");
    await writePluginSkill(alpha.pluginDir, "foo");
    await writePluginSkill(alpha.pluginDir, "foo.dotagents-managed");

    const result = await writePluginOutputs(["pi"], [alpha], root);

    expect(result).toEqual({ written: 2, warnings: [] });
    for (const name of ["foo", "foo.dotagents-managed"]) {
      await expectSymlinkTarget(
        join(root, ".agents", "skills", name),
        join(alpha.pluginDir, "skills", name),
      );
      expect(await readFile(
        join(root, ".agents", "skills", ".dotagents-managed", name),
        "utf-8",
      )).toBe(componentMarkerContent(
        join(root, ".agents", "skills", name),
        join(alpha.pluginDir, "skills", name),
      ));
    }
  });

  it("skips plugin skills paths that are not directories", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: {
        $schema: AGENT_PLUGIN_SCHEMA,
        name: "alpha-tools",
        description: "Portable tools",
      },
    });
    const skillsPath = join(alpha.pluginDir, "skills");
    await rm(skillsPath, { recursive: true });
    await writeFile(skillsPath, "not a directory");

    const result = await writePluginOutputs(["opencode", "claude"], [alpha], root);

    expect(result.written).toBe(2);
    expect(result.warnings).toContainEqual({
      agent: "opencode",
      name: "alpha-tools",
      message: `Plugin skills path is not a directory and was skipped: ${skillsPath}`,
    });
    const manifest = JSON.parse(await readFile(join(alpha.pluginDir, ".claude-plugin", "plugin.json"), "utf-8"));
    expect(manifest.skills).toBeUndefined();
  });

  it("does not advertise a skills file in generated Codex manifests", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: {
        $schema: AGENT_PLUGIN_SCHEMA,
        name: "alpha-tools",
        description: "Portable tools",
      },
    });
    const skillsPath = join(alpha.pluginDir, "skills");
    await rm(skillsPath, { recursive: true });
    await writeFile(skillsPath, "not a directory");

    await writePluginOutputs(["codex"], [alpha], root);

    const manifest = JSON.parse(
      await readFile(join(alpha.pluginDir, ".codex-plugin", "plugin.json"), "utf-8"),
    );
    expect(manifest.skills).toBeUndefined();
  });

  it("skips plugin agents paths that are not directories", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: { agents: "README.md" },
    });
    const agentsPath = join(alpha.pluginDir, "README.md");
    await writeFile(agentsPath, "not a directory");

    const result = await writePluginOutputs(["opencode"], [alpha], root);

    expect(result.written).toBe(0);
    expect(result.warnings).toContainEqual({
      agent: "opencode",
      name: "alpha-tools",
      message: `Plugin agents path is not a directory and was skipped: ${agentsPath}`,
    });
  });

  it("projects contained plugin skills directory symlinks", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: {
        $schema: AGENT_PLUGIN_SCHEMA,
        name: "alpha-tools",
        description: "Portable tools",
      },
    });
    const skillsPath = join(alpha.pluginDir, "skills");
    const linkedSkillsPath = join(alpha.pluginDir, "linked-skills");
    await rm(skillsPath, { recursive: true });
    await mkdir(join(linkedSkillsPath, "plugin-qa"), { recursive: true });
    await writeFile(
      join(linkedSkillsPath, "plugin-qa", "SKILL.md"),
      "---\nname: plugin-qa\ndescription: Linked skill\n---\n",
    );
    await symlink(relative(alpha.pluginDir, linkedSkillsPath), skillsPath);

    const result = await writePluginOutputs(["claude", "opencode", "pi"], [alpha], root);

    expect(result.warnings).toEqual([]);
    const manifest = JSON.parse(await readFile(join(alpha.pluginDir, ".claude-plugin", "plugin.json"), "utf-8"));
    expect(manifest.skills).toBe("./skills");
    await expectSymlinkTarget(join(root, ".opencode", "skills", "plugin-qa"), join(skillsPath, "plugin-qa"));
    await expectSymlinkTarget(join(root, ".agents", "skills", "plugin-qa"), join(skillsPath, "plugin-qa"));
  });

  it("projects explicit plugin component paths into OpenCode native locations", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: { skills: "components/skills", agents: "components/agents" },
    });
    await writePluginSkill(join(alpha.pluginDir, "components"), "plugin-qa");
    await mkdir(join(alpha.pluginDir, "components", "agents"), { recursive: true });
    await writeFile(
      join(alpha.pluginDir, "components", "agents", "plugin-reviewer.md"),
      "---\ndescription: Plugin reviewer\n---\nReview plugin output.\n",
      "utf-8",
    );

    const result = await writePluginOutputs(["opencode"], [alpha], root);

    expect(result.warnings).toEqual([]);
    expect(result.written).toBe(2);
    await expectSymlinkTarget(
      join(root, ".opencode", "skills", "plugin-qa"),
      join(alpha.pluginDir, "components", "skills", "plugin-qa"),
    );
    await expectSymlinkTarget(
      join(root, ".opencode", "agents", "plugin-reviewer.md"),
      join(alpha.pluginDir, "components", "agents", "plugin-reviewer.md"),
    );
  });

  it("projects plugin skills into Pi's native agentskills location", async () => {
    const alpha = await plugin("alpha-tools");
    await writePluginSkill(alpha.pluginDir, "plugin-qa");

    const result = await writePluginOutputs(["pi"], [alpha], root);

    expect(result.warnings).toEqual([]);
    expect(result.written).toBe(1);
    await expectSymlinkTarget(
      join(root, ".agents", "skills", "plugin-qa"),
      join(alpha.pluginDir, "skills", "plugin-qa"),
    );
  });

  it("warns and skips invalid Pi plugin skill names", async () => {
    const alpha = await plugin("alpha-tools");
    await mkdir(join(alpha.pluginDir, "skills", "bad"), { recursive: true });
    await writeFile(
      join(alpha.pluginDir, "skills", "bad", "SKILL.md"),
      `---\nname: ../../outside\ndescription: Bad skill\n---\n`,
      "utf-8",
    );

    const result = await writePluginOutputs(["pi"], [alpha], root);

    expect(result).toEqual({
      written: 0,
      warnings: [
        {
          agent: "pi",
          name: "alpha-tools",
          message: 'Plugin skill "../../outside" cannot be projected to Pi because skill names must start with alphanumeric and contain only [a-zA-Z0-9._-].',
        },
      ],
    });
    expect(existsSync(join(root, "outside"))).toBe(false);
    await expect(projectedPiSkillNames(["pi"], [alpha])).resolves.toEqual([]);
  });

  it("warns and skips unsafe plugin component paths for skill projections", async () => {
    const alpha = await plugin("alpha-tools", {
      manifest: {
        skills: "../outside",
      },
    });

    const result = await writePluginOutputs(["pi"], [alpha], root);

    expect(result).toEqual({
      written: 0,
      warnings: [
        {
          agent: "pi",
          name: "alpha-tools",
          message: 'Plugin component path "../outside" for "skills" is not a safe relative path and was skipped.',
        },
      ],
    });
    expect(existsSync(join(root, ".agents", "skills"))).toBe(false);
  });

  it("does not overwrite unmanaged Pi plugin skill projections", async () => {
    const alpha = await plugin("alpha-tools");
    await writePluginSkill(alpha.pluginDir, "plugin-qa");
    await mkdir(join(root, ".agents", "skills", "plugin-qa"), { recursive: true });
    await writeFile(join(root, ".agents", "skills", "plugin-qa", "SKILL.md"), "---\nname: plugin-qa\ndescription: Mine\n---\n", "utf-8");

    const result = await writePluginOutputs(["pi"], [alpha], root);

    expect(result).toEqual({
      written: 0,
      warnings: [
        {
          agent: "pi",
          name: "alpha-tools",
          message: `Pi plugin skill projection exists and is not managed by dotagents: ${join(root, ".agents", "skills", "plugin-qa")}`,
        },
      ],
    });
    expect((await lstat(join(root, ".agents", "skills", "plugin-qa"))).isDirectory()).toBe(true);
  });

  it("does not overwrite unmanaged OpenCode plugin component projections", async () => {
    const alpha = await plugin("alpha-tools");
    await writePluginSkill(alpha.pluginDir, "plugin-qa");
    await mkdir(join(root, ".opencode", "skills", "plugin-qa"), { recursive: true });
    await writeFile(join(root, ".opencode", "skills", "plugin-qa", "SKILL.md"), "---\nname: plugin-qa\ndescription: Mine\n---\n", "utf-8");

    const result = await writePluginOutputs(["opencode"], [alpha], root);

    expect(result).toEqual({
      written: 0,
      warnings: [
        {
          agent: "opencode",
          name: "alpha-tools",
          message: `OpenCode plugin skill projection exists and is not managed by dotagents: ${join(root, ".opencode", "skills", "plugin-qa")}`,
        },
      ],
    });
  });

  it("does not write through unmanaged component ownership marker symlinks", async () => {
    const alpha = await plugin("alpha-tools");
    await writePluginSkill(alpha.pluginDir, "plugin-qa");
    const skillsDir = join(root, ".opencode", "skills");
    const markerPath = join(skillsDir, ".dotagents-managed", "plugin-qa");
    const outsideFile = join(root, "outside-marker.txt");
    await mkdir(skillsDir, { recursive: true });
    await mkdir(dirname(markerPath), { recursive: true });
    await writeFile(outsideFile, "keep\n");
    await symlink(outsideFile, markerPath);

    const result = await writePluginOutputs(["opencode"], [alpha], root);

    expect(existsSync(join(skillsDir, "plugin-qa"))).toBe(false);
    expect(await readFile(outsideFile, "utf-8")).toBe("keep\n");
    expect((await lstat(markerPath)).isSymbolicLink()).toBe(true);
    expect(result.warnings).toContainEqual({
      agent: "opencode",
      name: "alpha-tools",
      message: `OpenCode plugin skill ownership marker exists and is not managed by dotagents: ${markerPath}`,
    });
  });

  it("does not write through symlinked component ownership directories", async () => {
    const alpha = await plugin("alpha-tools");
    await writePluginSkill(alpha.pluginDir, "plugin-qa");
    const skillsDir = join(root, ".opencode", "skills");
    const markerDir = join(skillsDir, ".dotagents-managed");
    const outsideDir = join(root, "outside-markers");
    await mkdir(skillsDir, { recursive: true });
    await mkdir(outsideDir, { recursive: true });
    await symlink(outsideDir, markerDir);

    const result = await writePluginOutputs(["opencode"], [alpha], root);

    expect(existsSync(join(skillsDir, "plugin-qa"))).toBe(false);
    expect(existsSync(join(outsideDir, "plugin-qa"))).toBe(false);
    expect((await lstat(markerDir)).isSymbolicLink()).toBe(true);
    expect(result.warnings).toContainEqual({
      agent: "opencode",
      name: "alpha-tools",
      message: `OpenCode plugin skill ownership marker exists and is not managed by dotagents: ${join(markerDir, "plugin-qa")}`,
    });
  });

  it("repairs dangling managed plugin component links", async () => {
    const alpha = await plugin("alpha-tools");
    await writePluginSkill(alpha.pluginDir, "plugin-qa");
    await mkdir(join(root, ".opencode", "skills"), { recursive: true });
    const linkPath = join(root, ".opencode", "skills", "plugin-qa");
    const missingTarget = join(root, ".agents", "plugins", "alpha-tools", "missing", "plugin-qa");
    await symlink(relative(dirname(linkPath), missingTarget), linkPath);
    await mkdir(join(root, ".opencode", "skills", ".dotagents-managed"), { recursive: true });
    await writeFile(
      join(root, ".opencode", "skills", ".dotagents-managed", "plugin-qa"),
      componentMarkerContent(linkPath, missingTarget),
    );

    const result = await writePluginOutputs(["opencode"], [alpha], root);

    expect(result.warnings).toEqual([]);
    expect(result.written).toBe(1);
    await expectSymlinkTarget(
      join(root, ".opencode", "skills", "plugin-qa"),
      join(alpha.pluginDir, "skills", "plugin-qa"),
    );
  });

  it("does not prune user links that resolve outside managed plugin roots", async () => {
    const outside = join(root, "outside", "plugin-qa");
    await mkdir(outside, { recursive: true });
    await mkdir(join(root, ".agents", "plugins"), { recursive: true });
    await symlink(join(root, "outside"), join(root, ".agents", "plugins", "redirect"));
    await mkdir(join(root, ".opencode", "skills"), { recursive: true });
    const linkPath = join(root, ".opencode", "skills", "plugin-qa");
    await symlink(
      relative(dirname(linkPath), join(root, ".agents", "plugins", "redirect", "plugin-qa")),
      linkPath,
    );

    const pruned = await prunePluginOutputs([], [], root);

    expect(pruned).not.toContain(linkPath);
    expect((await lstat(linkPath)).isSymbolicLink()).toBe(true);
  });

  it("does not prune through symlinked component ownership directories", async () => {
    const outsideTarget = join(root, "outside", "plugin-qa");
    const outsideMarkers = join(root, "outside-markers");
    const skillsDir = join(root, ".opencode", "skills");
    const linkPath = join(skillsDir, "plugin-qa");
    await mkdir(outsideTarget, { recursive: true });
    await mkdir(outsideMarkers, { recursive: true });
    await mkdir(skillsDir, { recursive: true });
    await writeFile(
      join(outsideMarkers, "plugin-qa"),
      componentMarkerContent(linkPath, outsideTarget),
    );
    await symlink(relative(skillsDir, outsideTarget), linkPath);
    await symlink(outsideMarkers, join(skillsDir, ".dotagents-managed"));

    const pruned = await prunePluginOutputs([], [], root);

    expect(pruned).not.toContain(linkPath);
    expect((await lstat(linkPath)).isSymbolicLink()).toBe(true);
    expect(await readFile(join(outsideMarkers, "plugin-qa"), "utf-8")).toBe(
      componentMarkerContent(linkPath, outsideTarget),
    );
  });

  it("ignores component projection roots that are files during pruning", async () => {
    const skillsPath = join(root, ".opencode", "skills");
    await mkdir(dirname(skillsPath), { recursive: true });
    await writeFile(skillsPath, "user-owned\n");

    await expect(prunePluginOutputs([], [], root)).resolves.toEqual([]);

    expect(await readFile(skillsPath, "utf-8")).toBe("user-owned\n");
  });

  it("removes orphan component markers before a later user link can inherit ownership", async () => {
    const alpha = await plugin("alpha-tools");
    await writePluginSkill(alpha.pluginDir, "plugin-qa");
    const linkPath = join(root, ".opencode", "skills", "plugin-qa");
    const markerPath = join(root, ".opencode", "skills", ".dotagents-managed", "plugin-qa");
    await writePluginOutputs(["opencode"], [alpha], root);
    await rm(linkPath);

    await prunePluginOutputs([], [], root);

    expect(existsSync(markerPath)).toBe(false);
    const userTarget = join(root, "user-skill");
    await mkdir(userTarget);
    await symlink(relative(dirname(linkPath), userTarget), linkPath);

    const pruned = await prunePluginOutputs([], [], root);

    expect(pruned).not.toContain(linkPath);
    expect((await lstat(linkPath)).isSymbolicLink()).toBe(true);
  });

  it("does not transfer a target-bound marker to a replacement user link", async () => {
    const alpha = await plugin("alpha-tools");
    await writePluginSkill(alpha.pluginDir, "plugin-qa");
    const linkPath = join(root, ".opencode", "skills", "plugin-qa");
    const markerPath = join(root, ".opencode", "skills", ".dotagents-managed", "plugin-qa");
    await writePluginOutputs(["opencode"], [alpha], root);
    await rm(linkPath);
    const userTarget = join(root, "user-skill");
    await mkdir(userTarget);
    await symlink(relative(dirname(linkPath), userTarget), linkPath);

    const pruned = await prunePluginOutputs([], [], root);

    expect(pruned).not.toContain(linkPath);
    expect((await lstat(linkPath)).isSymbolicLink()).toBe(true);
    expect(existsSync(markerPath)).toBe(false);
  });

  it("warns and skips invalid OpenCode plugin skill names", async () => {
    const alpha = await plugin("alpha-tools");
    await writePluginSkill(alpha.pluginDir, "plugin_qa");

    const result = await writePluginOutputs(["opencode"], [alpha], root);

    expect(result).toEqual({
      written: 0,
      warnings: [
        {
          agent: "opencode",
          name: "alpha-tools",
          message: 'Plugin skill "plugin_qa" cannot be projected to OpenCode because OpenCode skill names must be lowercase alphanumeric with single hyphen separators.',
        },
      ],
    });
    expect(existsSync(join(root, ".opencode", "skills", "plugin_qa"))).toBe(false);
  });

  it("prunes stale managed runtime plugin outputs", async () => {
    const alpha = await plugin("alpha-tools");
    await writePluginSkill(alpha.pluginDir, "plugin-qa");
    await writeFile(
      join(alpha.pluginDir, "agents", "plugin-reviewer.md"),
      "---\ndescription: Plugin reviewer\n---\nReview plugin output.\n",
      "utf-8",
    );
    await writePluginOutputs(["claude", "cursor", "codex", "grok", "opencode", "pi"], [alpha], root);

    const pruned = await prunePluginOutputs([], [alpha], root);

    expect(pruned).toEqual([
      join(root, ".agents", "plugins", "marketplace.json"),
      join(root, ".claude-plugin", "marketplace.json"),
      join(root, ".cursor-plugin", "marketplace.json"),
      join(root, ".grok", "plugins", "alpha-tools"),
      join(root, ".opencode", "skills", "plugin-qa"),
      join(root, ".opencode", "agents", "plugin-reviewer.md"),
      join(root, ".agents", "skills", "plugin-qa"),
      join(root, ".agents", "plugins", "alpha-tools", ".claude-plugin", "plugin.json"),
      join(root, ".agents", "plugins", "alpha-tools", ".cursor-plugin", "plugin.json"),
      join(root, ".agents", "plugins", "alpha-tools", ".codex-plugin", "plugin.json"),
    ]);
    expect(existsSync(join(root, ".agents", "plugins", "marketplace.json"))).toBe(false);
    expect(existsSync(join(root, ".claude-plugin", "marketplace.json"))).toBe(false);
    expect(existsSync(join(root, ".cursor-plugin", "marketplace.json"))).toBe(false);
    expect(existsSync(join(root, ".grok", "plugins", "alpha-tools"))).toBe(false);
    expect(existsSync(join(root, ".opencode", "skills", "plugin-qa"))).toBe(false);
    expect(existsSync(join(root, ".opencode", "agents", "plugin-reviewer.md"))).toBe(false);
    expect(existsSync(join(root, ".agents", "skills", "plugin-qa"))).toBe(false);
    expect(existsSync(join(root, ".agents", "plugins", "alpha-tools", ".claude-plugin", "plugin.json"))).toBe(false);
    expect(existsSync(join(root, ".agents", "plugins", "alpha-tools", ".cursor-plugin", "plugin.json"))).toBe(false);
    expect(existsSync(join(root, ".agents", "plugins", "alpha-tools", ".codex-plugin", "plugin.json"))).toBe(false);
  });

  it("does not prune arbitrary component links into canonical plugin sources", async () => {
    const localPlugin = join(root, ".agents", "plugins", "local-tools");
    await mkdir(join(localPlugin, "skills", "local-qa"), { recursive: true });
    await mkdir(join(root, ".opencode", "skills"), { recursive: true });
    await symlink(
      relative(join(root, ".opencode", "skills"), join(localPlugin, "skills", "local-qa")),
      join(root, ".opencode", "skills", "local-qa"),
    );

    const pruned = await prunePluginOutputs([], [], root);

    expect(pruned).toEqual([]);
    await expectSymlinkTarget(
      join(root, ".opencode", "skills", "local-qa"),
      join(localPlugin, "skills", "local-qa"),
    );
  });

});
