import { writeFile } from "node:fs/promises";
import { stringify } from "smol-toml";
import type { Lockfile } from "./schema.js";

const HEADER = "# Auto-generated by dotagents. Do not edit.\n";

type WritableLockfile = Omit<Lockfile, "subagents" | "plugins"> & {
  subagents?: Lockfile["subagents"];
  plugins?: Lockfile["plugins"];
};

/**
 * Write an agents.lock file.
 * Managed entries are sorted alphabetically for deterministic output.
 */
export async function writeLockfile(
  filePath: string,
  lockfile: WritableLockfile,
): Promise<void> {
  // Sort skills by name for deterministic output
  const sortedSkills: Record<string, unknown> = {};
  for (const name of Object.keys(lockfile.skills).toSorted()) {
    sortedSkills[name] = lockfile.skills[name];
  }
  const sortedSubagents: Record<string, unknown> = {};
  const subagents = lockfile.subagents ?? {};
  for (const name of Object.keys(subagents).toSorted()) {
    sortedSubagents[name] = subagents[name];
  }
  const sortedPlugins: Record<string, unknown> = {};
  const plugins = lockfile.plugins ?? {};
  for (const name of Object.keys(plugins).toSorted()) {
    sortedPlugins[name] = plugins[name];
  }

  const doc: Record<string, unknown> = {
    version: lockfile.version,
    skills: sortedSkills,
  };
  if (Object.keys(sortedSubagents).length > 0) {
    doc["subagents"] = sortedSubagents;
  }
  if (Object.keys(sortedPlugins).length > 0) {
    doc["plugins"] = sortedPlugins;
  }

  const toml = stringify(doc);
  await writeFile(filePath, `${(HEADER + toml).trimEnd()}\n`, "utf-8");
}
