import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Security - dotagents",
  description: "Trust policies and security model for dotagents",
};

export default function SecurityPage() {
  return (
    <>
      <section className="section" id="trust" style={{ borderTop: "none" }}>
        <h2>Trust Policies</h2>
        <p>
          The <code>[trust]</code> section in <code>agents.toml</code> controls
          which skill sources are allowed. Trust is validated before any network
          operations in <code>add</code> and <code>install</code>. If a source
          does not match the policy, the command fails immediately.
        </p>

        <h3>No Trust Section (default)</h3>
        <p>
          When <code>[trust]</code> is absent, all sources are allowed. This is
          the default for backward compatibility.
        </p>
        <pre>
          <code>{`# No [trust] section — all sources allowed
version = 1
agents = ["claude"]

[[skills]]
name = "any-skill"
source = "anyone/any-repo"`}</code>
        </pre>

        <h3>Allowlist Mode</h3>
        <p>
          Add a <code>[trust]</code> section to restrict sources to an
          allowlist. A source passes if it matches any rule.
        </p>
        <pre>
          <code>{`[trust]
github_orgs = ["getsentry", "my-company"]
github_repos = ["external-org/one-approved-repo"]
git_domains = ["git.corp.example.com"]`}</code>
        </pre>
        <table>
          <thead>
            <tr>
              <th>Field</th>
              <th>Matches</th>
              <th>Example</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <code>github_orgs</code>
              </td>
              <td>
                GitHub sources where the owner matches
              </td>
              <td>
                <code>&quot;getsentry&quot;</code> matches{" "}
                <code>getsentry/skills</code>,{" "}
                <code>getsentry/warden</code>
              </td>
            </tr>
            <tr>
              <td>
                <code>github_repos</code>
              </td>
              <td>
                Exact <code>owner/repo</code> match
              </td>
              <td>
                <code>&quot;external-org/one-approved-repo&quot;</code>
              </td>
            </tr>
            <tr>
              <td>
                <code>git_domains</code>
              </td>
              <td>
                Domain extracted from <code>git:</code> URLs
              </td>
              <td>
                <code>&quot;git.corp.example.com&quot;</code> matches{" "}
                <code>git:https://git.corp.example.com/team/repo</code>
              </td>
            </tr>
          </tbody>
        </table>
        <p>
          Local <code>path:</code> sources are always allowed regardless of
          trust configuration.
        </p>
        <p>
          You can also manage trusted sources from the CLI instead of editing
          TOML directly:
        </p>
        <pre>
          <code>{`dotagents trust add getsentry                    # trust a GitHub org
dotagents trust add external-org/specific-repo   # trust a specific repo
dotagents trust add git.corp.example.com         # trust a git domain
dotagents trust list                             # show trusted sources`}</code>
        </pre>

        <h3>Explicit Allow All</h3>
        <p>
          Use <code>allow_all = true</code> to make the intent explicit in
          shared repositories. This is functionally the same as omitting the
          section, but communicates that the choice was deliberate.
        </p>
        <pre>
          <code>{`[trust]
allow_all = true`}</code>
        </pre>
      </section>

      <section className="section" id="lockfile">
        <h2>Lockfile</h2>
        <p>
          <code>agents.lock</code> tracks which skills are managed and where
          they came from. It is auto-generated and should be gitignored.
        </p>
        <pre>
          <code>{`# Auto-generated by dotagents. Do not edit.
version = 1

[skills.find-bugs]
source = "getsentry/skills"
resolved_url = "https://github.com/getsentry/skills.git"
resolved_path = "plugins/sentry-skills/skills/find-bugs"`}</code>
        </pre>
        <table>
          <thead>
            <tr>
              <th>Field</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <code>source</code>
              </td>
              <td>Original source from agents.toml</td>
            </tr>
            <tr>
              <td>
                <code>resolved_url</code>
              </td>
              <td>Resolved git clone URL</td>
            </tr>
            <tr>
              <td>
                <code>resolved_path</code>
              </td>
              <td>Subdirectory within repo where skill was found</td>
            </tr>
            <tr>
              <td>
                <code>resolved_ref</code>
              </td>
              <td>Resolved ref name (omitted for default branch)</td>
            </tr>
          </tbody>
        </table>
        <p>
          Local <code>path:</code> skills have <code>source</code> only.
        </p>
      </section>

      <section className="section" id="caching">
        <h2>Caching</h2>
        <p>
          Cloned repositories are cached at{" "}
          <code>~/.local/dotagents/</code> (override with{" "}
          <code>DOTAGENTS_STATE_DIR</code>).
        </p>
        <ul>
          <li>
            Shallow clone per repo, refreshed after a 24-hour TTL
          </li>
          <li>
            All git operations are non-interactive (
            <code>GIT_TERMINAL_PROMPT=0</code>)
          </li>
          <li>
            Use <code>dotagents install --force</code> to bypass cache
          </li>
        </ul>
      </section>
    </>
  );
}
