import { stringify as tomlStringify } from "smol-toml";
import type { McpDeclaration, HookDeclaration } from "../types.js";

export const DOTAGENTS_SUBAGENT_MARKER = "Generated by dotagents. Edit agents.toml instead.";
const DOTAGENTS_SUBAGENT_MARKER_RE = escapeRegExp(DOTAGENTS_SUBAGENT_MARKER);
const MANAGED_MARKDOWN_SUBAGENT_RE = new RegExp(
  `^\\uFEFF?---[ \\t]*\\r?\\n# ${DOTAGENTS_SUBAGENT_MARKER_RE}\\r?\\n`,
);
const MANAGED_TOML_SUBAGENT_RE = new RegExp(
  `^\\uFEFF?# ${DOTAGENTS_SUBAGENT_MARKER_RE}\\r?\\n`,
);

export function envRecord(
  env: string[] | undefined,
  template: (key: string) => string,
): Record<string, string> | undefined {
  if (!env || env.length === 0) {return undefined;}
  const rec: Record<string, string> = {};
  for (const key of env) {rec[key] = template(key);}
  return rec;
}

const ENV_REF_RE = /\$\{([A-Za-z_][A-Za-z0-9_]*)\}/g;

export function interpolateEnvRefs(
  value: string,
  template: (varName: string) => string,
): string {
  return value.replace(ENV_REF_RE, (_match, varName: string) => template(varName));
}

export function interpolateHeaders(
  headers: Record<string, string> | undefined,
  template: (varName: string) => string,
): Record<string, string> | undefined {
  if (!headers) {return undefined;}
  const result: Record<string, string> = {};
  for (const [key, value] of Object.entries(headers)) {
    result[key] = interpolateEnvRefs(value, template);
  }
  return result;
}

/**
 * Split headers for Codex's model: pure `${VAR}` refs go to `envHttpHeaders`
 * (mapping env var name → header name), everything else stays in `httpHeaders`.
 * Mixed values like `"Bearer ${TOKEN}"` can't be represented in Codex's
 * env_http_headers format and fall through as literal strings in httpHeaders.
 */
export function extractCodexHeaders(
  headers: Record<string, string> | undefined,
): { httpHeaders?: Record<string, string>; envHttpHeaders?: Record<string, string> } {
  if (!headers) {return {};}
  let httpHeaders: Record<string, string> | undefined;
  let envHttpHeaders: Record<string, string> | undefined;
  const pureRefRe = /^\$\{([A-Za-z_][A-Za-z0-9_]*)\}$/;
  for (const [key, value] of Object.entries(headers)) {
    const match = pureRefRe.exec(value);
    if (match) {
      (envHttpHeaders ??= {})[match[1]!] = key;
    } else {
      (httpHeaders ??= {})[key] = value;
    }
  }
  return { httpHeaders, envHttpHeaders };
}

export function httpServer(
  s: McpDeclaration,
  type?: string,
  template?: (varName: string) => string,
): [string, unknown] {
  const tpl = template ?? ((k: string) => `\${${k}}`);
  return [
    s.name,
    {
      ...(type && { type }),
      url: interpolateEnvRefs(s.url!, tpl),
      ...(s.headers && { headers: interpolateHeaders(s.headers, tpl) }),
    },
  ];
}

/**
 * Serialize hooks into Claude Code / VS Code settings.json format.
 *
 * Output shape:
 * {
 *   "PreToolUse": [{ "matcher": "Bash", "hooks": [{ "type": "command", "command": "..." }] }],
 *   "Stop": [{ "hooks": [{ "type": "command", "command": "..." }] }]
 * }
 */
export function serializeClaudeHooks(hooks: HookDeclaration[]): Record<string, unknown> {
  const result: Record<string, unknown[]> = {};
  for (const h of hooks) {
    const entry = {
      ...(h.matcher && { matcher: h.matcher }),
      hooks: [{ type: "command", command: h.command }],
    };
    (result[h.event] ??= []).push(entry);
  }
  return result;
}

export function serializeMarkdownSubagent(
  fields: Record<string, unknown>,
  instructions: string,
): string {
  const lines = ["---", `# ${DOTAGENTS_SUBAGENT_MARKER}`];

  for (const [key, value] of Object.entries(fields)) {
    appendYamlField(lines, key, value);
  }

  lines.push("---", "", instructions.trim(), "");
  return lines.join("\n");
}

/** Insert the dotagents marker into markdown subagent frontmatter. */
export function markManagedMarkdownSubagent(content: string): string {
  if (hasDotagentsMarkdownSubagentMarker(content)) {return content;}
  const marked = content.replace(
    /^(\uFEFF?---[ \t]*\r?\n)/,
    (opening) => `${opening}# ${DOTAGENTS_SUBAGENT_MARKER}\n`,
  );
  if (marked !== content) {return marked;}

  const hasBom = content.startsWith("\uFEFF");
  const body = hasBom ? content.slice(1) : content;
  return `${hasBom ? "\uFEFF" : ""}---\n# ${DOTAGENTS_SUBAGENT_MARKER}\n---\n\n${body}`;
}

/** Whether Markdown content has the dotagents marker in its generated frontmatter header. */
export function hasDotagentsMarkdownSubagentMarker(content: string): boolean {
  return MANAGED_MARKDOWN_SUBAGENT_RE.test(content);
}

/** Whether TOML content has the dotagents marker in its generated header. */
export function hasDotagentsTomlSubagentMarker(content: string): boolean {
  return MANAGED_TOML_SUBAGENT_RE.test(content);
}

export function serializeCodexSubagent(
  fields: Record<string, unknown>,
): string {
  const doc: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(fields)) {
    if (value !== undefined) {
      doc[key] = value;
    }
  }

  return `# ${DOTAGENTS_SUBAGENT_MARKER}\n${tomlStringify(doc)}`;
}

export function markManagedTomlSubagent(content: string): string {
  if (hasDotagentsTomlSubagentMarker(content)) {return content;}
  return `# ${DOTAGENTS_SUBAGENT_MARKER}\n${content}`;
}

function escapeRegExp(value: string): string {
  return value.replaceAll(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function appendYamlField(
  lines: string[],
  key: string,
  value: unknown,
  indent = 0,
): void {
  if (value === undefined) {return;}

  const prefix = " ".repeat(indent);
  if (isPlainObject(value)) {
    const entries = Object.entries(value);
    if (entries.length === 0) {
      lines.push(`${prefix}${toYamlKey(key)}: {}`);
      return;
    }
    lines.push(`${prefix}${toYamlKey(key)}:`);
    for (const [childKey, childValue] of entries) {
      appendYamlField(lines, childKey, childValue, indent + 2);
    }
    return;
  }

  if (typeof value === "string" && value.includes("\n")) {
    const chomp = value.endsWith("\n") ? "|+" : "|-";
    const body = value;
    lines.push(`${prefix}${toYamlKey(key)}: ${chomp}`);
    for (const line of body.split(/\r?\n/)) {
      lines.push(`${prefix}  ${line}`);
    }
    return;
  }

  const serialized = JSON.stringify(value);
  if (serialized !== undefined) {
    lines.push(`${prefix}${toYamlKey(key)}: ${serialized}`);
  }
}

function toYamlKey(key: string): string {
  if (/^[A-Za-z_][A-Za-z0-9_-]*$/.test(key)) {
    return key;
  }
  return JSON.stringify(key);
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
