import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

const HEADER = `# Auto-generated by dotagents. Do not edit.
# Managed artifacts (installed by dotagents)`;

/**
 * Generate .agents/.gitignore listing managed skill directories and installed subagents.
 * Skills with path: sources are also gitignored since they're installed by dotagents.
 */
export async function writeAgentsGitignore(
  agentsDir: string,
  managedSkillNames: string[],
  managedSubagentNames: string[] = [],
  managedPluginNames: string[] = [],
): Promise<void> {
  const lines = [HEADER];
  for (const name of managedSkillNames.toSorted()) {
    lines.push(`/skills/${name}/`);
  }
  for (const name of managedSubagentNames.toSorted()) {
    lines.push(`/agents/${name}.md`);
  }
  for (const name of managedPluginNames.toSorted()) {
    lines.push(`/plugins/${name}/`);
  }
  lines.push(""); // trailing newline

  await writeFile(join(agentsDir, ".gitignore"), lines.join("\n"), "utf-8");
}

/**
 * Entries that should be in the project root .gitignore.
 * agents.lock and .agents/.gitignore are auto-generated and should not be committed.
 */
const ROOT_GITIGNORE_ENTRIES = ["agents.lock", ".agents/.gitignore"] as const;

const ROOT_GITIGNORE_COMMENT = "# Auto-generated by dotagents — do not commit these files.";

/**
 * Check which root .gitignore entries are missing.
 * Returns the list of entries not present (empty if all present).
 */
export async function checkRootGitignoreEntries(projectRoot: string): Promise<string[]> {
  const gitignorePath = join(projectRoot, ".gitignore");

  let content = "";
  if (existsSync(gitignorePath)) {
    content = await readFile(gitignorePath, "utf-8");
  }

  const lines = new Set(content.split("\n").map((l) => l.trim()));
  const missing: string[] = [];
  for (const entry of ROOT_GITIGNORE_ENTRIES) {
    if (!lines.has(entry)) {
      missing.push(entry);
    }
  }

  return missing;
}

/**
 * Ensure the root .gitignore contains entries for agents.lock and .agents/.gitignore.
 * Writes missing entries. Returns the list of entries that were added.
 */
export async function ensureRootGitignoreEntries(projectRoot: string): Promise<string[]> {
  const gitignorePath = join(projectRoot, ".gitignore");
  const missing = await checkRootGitignoreEntries(projectRoot);

  if (missing.length === 0) {return [];}

  let content = "";
  if (existsSync(gitignorePath)) {
    content = await readFile(gitignorePath, "utf-8");
  }

  const suffix = content.length > 0 && !content.endsWith("\n") ? "\n" : "";
  const block = `${ROOT_GITIGNORE_COMMENT}\n${missing.join("\n")}\n`;
  await writeFile(gitignorePath, `${content}${suffix}${block}`, "utf-8");

  return missing;
}
