import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, readFile, rm, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { writeAgentsGitignore, checkRootGitignoreEntries, ensureRootGitignoreEntries } from "./writer.js";

describe("writeAgentsGitignore", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), "dotagents-test-"));
    await mkdir(join(dir, ".agents"), { recursive: true });
  });

  afterEach(async () => {
    await rm(dir, { recursive: true });
  });

  it("writes header with no managed skills", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, []);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    expect(content).toContain("Auto-generated by dotagents");
    expect(content.split("\n").filter((l) => l.startsWith("/skills/"))).toEqual([
      "/skills/.dotagents-managed/",
    ]);
  });

  it("lists managed skill directories", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, ["pdf", "find-bugs", "code-review"]);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    expect(content).toContain("/skills/code-review");
    expect(content).toContain("/skills/find-bugs");
    expect(content).toContain("/skills/pdf");
  });

  it("lists managed subagent files", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, [], ["reviewer", "test-runner"]);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    expect(content).toContain("/agents/reviewer.md");
    expect(content).toContain("/agents/test-runner.md");
  });

  it("lists managed plugin directories", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, [], [], ["review-tools"]);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    expect(content).toContain("/plugins/review-tools/");
    expect(content).toContain("/plugin-data/");
    expect(content).toContain("/plugin-mcp/");
    expect(content).not.toContain("/plugins/marketplace.json");
  });

  it("sorts skill names alphabetically", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, ["zebra", "alpha", "middle"]);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    const lines = content.split("\n").filter((l) => l.startsWith("/skills/"));
    expect(lines).toEqual([
      "/skills/.dotagents-managed/",
      "/skills/alpha",
      "/skills/middle",
      "/skills/zebra",
    ]);
  });

  it("overwrites existing gitignore", async () => {
    const agentsDir = join(dir, ".agents");
    await writeAgentsGitignore(agentsDir, ["old-skill"]);
    await writeAgentsGitignore(agentsDir, ["new-skill"]);

    const content = await readFile(join(agentsDir, ".gitignore"), "utf-8");
    expect(content).not.toContain("old-skill");
    expect(content).toContain("new-skill");
  });
});

describe("checkRootGitignoreEntries", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), "dotagents-test-"));
  });

  afterEach(async () => {
    await rm(dir, { recursive: true });
  });

  it("returns all entries when no .gitignore exists", async () => {
    const missing = await checkRootGitignoreEntries(dir);
    expect(missing).toContain("agents.lock");
    expect(missing).toContain(".agents/.gitignore");
  });

  it("returns missing entries", async () => {
    await writeFile(join(dir, ".gitignore"), "agents.lock\n", "utf-8");
    const missing = await checkRootGitignoreEntries(dir);
    expect(missing).toEqual([".agents/.gitignore"]);
  });

  it("returns empty when all entries present", async () => {
    await writeFile(join(dir, ".gitignore"), "agents.lock\n.agents/.gitignore\n", "utf-8");
    const missing = await checkRootGitignoreEntries(dir);
    expect(missing).toEqual([]);
  });
});

describe("ensureRootGitignoreEntries", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), "dotagents-test-"));
  });

  afterEach(async () => {
    await rm(dir, { recursive: true });
  });

  it("creates .gitignore with entries when missing", async () => {
    const added = await ensureRootGitignoreEntries(dir);
    expect(added).toContain("agents.lock");
    expect(added).toContain(".agents/.gitignore");

    const content = await readFile(join(dir, ".gitignore"), "utf-8");
    expect(content).toContain("agents.lock");
    expect(content).toContain(".agents/.gitignore");
  });

  it("appends missing entries to existing .gitignore", async () => {
    await writeFile(join(dir, ".gitignore"), "node_modules/\n", "utf-8");
    await ensureRootGitignoreEntries(dir);

    const content = await readFile(join(dir, ".gitignore"), "utf-8");
    expect(content).toContain("node_modules/");
    expect(content).toContain("agents.lock");
  });

  it("is a no-op when entries already present", async () => {
    await writeFile(join(dir, ".gitignore"), "agents.lock\n.agents/.gitignore\n", "utf-8");
    const added = await ensureRootGitignoreEntries(dir);
    expect(added).toEqual([]);
  });
});
