import { readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

const HEADER = `# Auto-generated by dotagents. Do not edit.
# Managed skills (installed by dotagents)`;

/**
 * Generate .agents/.gitignore listing managed skill directories.
 * Skills with path: sources are also gitignored since they're installed by dotagents.
 */
export async function writeAgentsGitignore(
  agentsDir: string,
  managedSkillNames: string[],
): Promise<void> {
  const lines = [HEADER];
  for (const name of managedSkillNames.toSorted()) {
    lines.push(`/skills/${name}/`);
  }
  lines.push(""); // trailing newline

  await writeFile(join(agentsDir, ".gitignore"), lines.join("\n"), "utf-8");
}

/**
 * Remove .agents/.gitignore if it exists.
 */
export async function removeAgentsGitignore(agentsDir: string): Promise<void> {
  const gitignorePath = join(agentsDir, ".gitignore");
  if (existsSync(gitignorePath)) {
    await rm(gitignorePath);
  }
}

/**
 * Create or remove .agents/.gitignore based on the gitignore config option.
 * When gitignore is true, generates the gitignore listing managed skills.
 * When gitignore is false, removes the gitignore file if it exists.
 */
export async function updateAgentsGitignore(
  agentsDir: string,
  gitignore: boolean,
  managedSkillNames: string[],
): Promise<void> {
  if (gitignore) {
    await writeAgentsGitignore(agentsDir, managedSkillNames);
  } else {
    await removeAgentsGitignore(agentsDir);
  }
}

/**
 * Entries that should be in the project root .gitignore.
 * agents.lock and .agents/.gitignore are auto-generated and should not be committed.
 */
const ROOT_GITIGNORE_ENTRIES = ["agents.lock", ".agents/.gitignore"] as const;

const ROOT_GITIGNORE_COMMENT = "# Auto-generated by dotagents — do not commit these files.";

/**
 * Ensure the root .gitignore contains entries for agents.lock and .agents/.gitignore.
 * Returns the list of entries that were missing (empty if all present).
 */
export async function ensureRootGitignoreEntries(projectRoot: string): Promise<string[]> {
  const gitignorePath = join(projectRoot, ".gitignore");
  const missing: string[] = [];

  let content = "";
  if (existsSync(gitignorePath)) {
    content = await readFile(gitignorePath, "utf-8");
  }

  const lines = new Set(content.split("\n").map((l) => l.trim()));
  for (const entry of ROOT_GITIGNORE_ENTRIES) {
    if (!lines.has(entry)) {
      missing.push(entry);
    }
  }

  if (missing.length === 0) {return [];}

  const suffix = content.length > 0 && !content.endsWith("\n") ? "\n" : "";
  const prefix = content.length > 0 ? "" : "";
  const block = `${ROOT_GITIGNORE_COMMENT}\n${missing.join("\n")}\n`;
  await writeFile(gitignorePath, `${content}${suffix}${prefix}${block}`, "utf-8");

  return missing;
}
